//! Rendering of resume content (bio, skills, experience sections) into the
//! `% {INJECT_*}` placeholders of a document generated by
//! [`super::layout::generate_document`].

use crate::db::models::EducationDetails;

/// One renderable resume entry (an experience with its bullets, plus optional
/// structured education details). Serialized as-is to the frontend for the
/// HTML preview.
#[derive(Debug, Clone, serde::Serialize)]
pub struct ResumeEntry {
    pub title: String,
    pub org: Option<String>,
    pub start: Option<String>,
    pub end: Option<String>,
    pub bullets: Vec<String>,
    pub education: Option<EducationDetails>,
}

/// A resume section ready to render: heading plus its entries in display
/// order. Serialized to the frontend for the HTML preview.
#[derive(Debug, Clone, serde::Serialize)]
pub struct SectionGroup {
    pub heading: String,
    pub entries: Vec<ResumeEntry>,
}

/// Escape characters that break LaTeX compilation when they appear in user
/// content (`& % # _ $ ~ ^`). Backslash and braces are deliberately left
/// untouched so intentional inline LaTeX (e.g. `\textbf{...}`) keeps working.
pub fn escape_latex(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("\\&"),
            '%' => out.push_str("\\%"),
            '#' => out.push_str("\\#"),
            '_' => out.push_str("\\_"),
            '$' => out.push_str("\\$"),
            '~' => out.push_str("\\textasciitilde{}"),
            '^' => out.push_str("\\textasciicircum{}"),
            _ => out.push(c),
        }
    }
    out
}

/// Escape `s` for LaTeX, additionally turning URLs and email addresses into
/// clickable `\href{...}{...}` links. Requires `hyperref` in the preamble (see
/// [`super::layout::generate_layout_block`]). Text that isn't a link is escaped
/// exactly as [`escape_latex`] would, so the inline-LaTeX escape hatch (raw
/// `\` and `{}`) still works for hand-written content.
pub fn linkify_latex(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while !rest.is_empty() {
        // Emit leading whitespace verbatim (it holds no LaTeX-special chars),
        // then peel off the next whitespace-delimited word and render it.
        let word_start = rest.find(|c: char| !c.is_whitespace()).unwrap_or(rest.len());
        out.push_str(&rest[..word_start]);
        rest = &rest[word_start..];
        if rest.is_empty() {
            break;
        }
        let word_end = rest.find(|c: char| c.is_whitespace()).unwrap_or(rest.len());
        out.push_str(&render_word(&rest[..word_end]));
        rest = &rest[word_end..];
    }
    out
}

/// Render one whitespace-free token: a link when its core is a URL or email,
/// otherwise plain escaped text. Surrounding punctuation (the parentheses in
/// `(https://x.com)`, a trailing period, …) is escaped and kept outside the
/// link so it doesn't become part of the clickable target.
fn render_word(word: &str) -> String {
    const LEADING: &[char] = &['(', '[', '{', '"', '\'', '<'];
    const TRAILING: &[char] = &['.', ',', ';', ':', '!', '?', ')', ']', '}', '"', '\'', '>'];

    let without_lead = word.trim_start_matches(LEADING);
    let pre = &word[..word.len() - without_lead.len()];
    let core = without_lead.trim_end_matches(TRAILING);
    let post = &without_lead[core.len()..];

    match link_target(core) {
        Some(target) => format!(
            "{}\\href{{{}}}{{{}}}{}",
            escape_latex(pre),
            target,
            escape_latex(core),
            escape_latex(post),
        ),
        None => escape_latex(word),
    }
}

/// The `\href` target for a token, or `None` if it isn't a link. Full URLs are
/// used as-is (hyperref normalizes their special characters); a `www.` prefix
/// gets an `https://` scheme and a bare email gets `mailto:`.
fn link_target(core: &str) -> Option<String> {
    // A brace or backslash would break the `\href{...}` argument — don't risk it.
    if core.contains(|c| c == '{' || c == '}' || c == '\\') {
        return None;
    }
    let lower = core.to_ascii_lowercase();
    if lower.starts_with("http://") || lower.starts_with("https://") {
        Some(core.to_string())
    } else if lower.starts_with("www.") && core.len() > 4 {
        Some(format!("https://{}", core))
    } else if is_email(core) {
        Some(format!("mailto:{}", core))
    } else {
        None
    }
}

/// Conservative "looks like `local@domain.tld`" check (no scheme), kept strict
/// so ordinary text like `R&D@home` or a Twitter `@handle` isn't linkified.
fn is_email(core: &str) -> bool {
    let mut parts = core.splitn(2, '@');
    let (Some(local), Some(domain)) = (parts.next(), parts.next()) else {
        return false;
    };
    !local.is_empty()
        && domain.contains('.')
        && !domain.starts_with('.')
        && !domain.ends_with('.')
        && !core.contains("://")
}

/// Map a raw DB category string to a canonical section heading.
pub fn normalize_category(raw: &str) -> String {
    match raw.trim().to_lowercase().as_str() {
        "work" | "professional experience" | "job" | "employment" => {
            "Professional Experience".to_string()
        }
        "education" | "school" | "academic" => "Education".to_string(),
        "project" | "projects" => "Projects".to_string(),
        "competition" | "competitions" => "Competitions".to_string(),
        "leadership" => "Leadership".to_string(),
        "volunteer" | "volunteering" | "volunteer experience" => "Volunteer Experience".to_string(),
        other => {
            // Title-case each word
            other
                .split_whitespace()
                .map(|w| {
                    let mut c = w.chars();
                    match c.next() {
                        None => String::new(),
                        Some(f) => f.to_uppercase().to_string() + c.as_str(),
                    }
                })
                .collect::<Vec<_>>()
                .join(" ")
        }
    }
}

/// Default section ordering used when the user hasn't customised it.
pub fn default_section_order() -> Vec<&'static str> {
    vec![
        "Education",
        "Professional Experience",
        "Projects",
        "Competitions",
        "Leadership",
        "Volunteer Experience",
    ]
}

fn format_date_range(start: &Option<String>, end: &Option<String>) -> String {
    match (start, end) {
        (Some(s), Some(e)) if !s.is_empty() && !e.is_empty() => {
            format!("{} -- {}", escape_latex(s), escape_latex(e))
        }
        (Some(s), _) if !s.is_empty() => escape_latex(s),
        (_, Some(e)) if !e.is_empty() => escape_latex(e),
        _ => String::new(),
    }
}

fn render_entry(output: &mut String, entry: &ResumeEntry) {
    // Education entries headline the institution (org); everything else
    // headlines "Title -- Org".
    let header = if entry.education.is_some() {
        match &entry.org {
            Some(o) if !o.is_empty() => escape_latex(o),
            _ => escape_latex(&entry.title),
        }
    } else {
        match &entry.org {
            Some(o) if !o.is_empty() => {
                format!("{} -- {}", escape_latex(&entry.title), escape_latex(o))
            }
            _ => escape_latex(&entry.title),
        }
    };

    let date_str = format_date_range(&entry.start, &entry.end);
    if date_str.is_empty() {
        output.push_str(&format!("\\subsection*{{{}}}\n", header));
    } else {
        output.push_str(&format!("\\subsection*{{{} \\hfill {}}}\n", header, date_str));
    }

    if let Some(edu) = &entry.education {
        let degree = edu.degree.as_deref().unwrap_or("").trim().to_string();
        let gpa = edu.gpa.as_deref().unwrap_or("").trim().to_string();
        let coursework = edu.coursework.as_deref().unwrap_or("").trim().to_string();
        let honors = edu.honors.as_deref().unwrap_or("").trim().to_string();

        let mut degree_line = Vec::new();
        if !degree.is_empty() {
            degree_line.push(escape_latex(&degree));
        } else if entry.org.as_deref().map_or(false, |o| !o.is_empty()) {
            // Institution took the headline; fall back to the title as the degree line.
            degree_line.push(escape_latex(&entry.title));
        }
        if !gpa.is_empty() {
            degree_line.push(format!("GPA: {}", escape_latex(&gpa)));
        }
        if !degree_line.is_empty() {
            output.push_str(&format!("{} \\par\n", degree_line.join(" \\textbar{} ")));
        }
        if !coursework.is_empty() {
            output.push_str(&format!(
                "\\emph{{Relevant Coursework:}} {} \\par\n",
                escape_latex(&coursework)
            ));
        }
        if !honors.is_empty() {
            output.push_str(&format!("\\emph{{Honors:}} {} \\par\n", escape_latex(&honors)));
        }
    }

    if !entry.bullets.is_empty() {
        output.push_str("\\begin{itemize}\n");
        for bullet in &entry.bullets {
            output.push_str(&format!("\\item {}\n", linkify_latex(bullet)));
        }
        output.push_str("\\end{itemize}\n");
    }

    output.push_str("\\expvspace\n");
}

/// Inject grouped experience sections into `% {INJECT_SECTIONS}`.
///
/// `groups` is already sorted in the desired display order.
pub fn inject_sections_by_category(template: &str, groups: &[SectionGroup]) -> String {
    let mut output = String::new();

    for group in groups {
        if group.entries.is_empty() {
            continue;
        }

        output.push_str(&format!("\\section*{{{}}}\n", escape_latex(&group.heading)));

        for entry in &group.entries {
            render_entry(&mut output, entry);
        }
    }

    template.replace("% {INJECT_SECTIONS}", &output)
}

pub fn inject_skills_section(template: &str, categories: &[(String, Vec<String>)]) -> String {
    if categories.is_empty() {
        return template.replace("% {INJECT_SKILLS_HERE}", "");
    }

    let mut section = String::from("\\section*{Skills}\n");
    for (category, skills) in categories {
        let joined = skills
            .iter()
            .map(|s| escape_latex(s))
            .collect::<Vec<_>>()
            .join(", ");
        section.push_str(&format!(
            "\\textbf{{{}:}} {} \\par\n",
            escape_latex(category),
            joined
        ));
    }
    section.push_str("\\expvspace\n");

    template.replace("% {INJECT_SKILLS_HERE}", &section)
}

pub fn inject_bio_header(template: &str, name: &str, details: &[String]) -> String {
    let mut header = String::from("\\begin{center}\n");
    if !name.is_empty() {
        header.push_str(&format!(
            "    {{\\namesize \\textbf{{{}}}}} \\\\\n    \\vspace{{2pt}}\n",
            escape_latex(name)
        ));
    }

    let joined = details
        .iter()
        .map(|d| linkify_latex(d))
        .collect::<Vec<_>>()
        .join(" $\\cdot$ ");
    if !joined.is_empty() {
        header.push_str(&format!("    {} \\\\\n", joined));
    }
    header.push_str("\\end{center}\n\\headerdivider\n\\vspace{10pt}");

    template.replace("% {INJECT_BIO_HEADER}", &header)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(title: &str, org: Option<&str>, bullets: Vec<&str>) -> ResumeEntry {
        ResumeEntry {
            title: title.to_string(),
            org: org.map(|s| s.to_string()),
            start: Some("Jan 2020".to_string()),
            end: Some("Present".to_string()),
            bullets: bullets.into_iter().map(|s| s.to_string()).collect(),
            education: None,
        }
    }

    #[test]
    fn test_normalize_category() {
        assert_eq!(normalize_category("Work"), "Professional Experience");
        assert_eq!(normalize_category("work"), "Professional Experience");
        assert_eq!(normalize_category("project"), "Projects");
        assert_eq!(normalize_category("education"), "Education");
        assert_eq!(normalize_category("competition"), "Competitions");
        assert_eq!(normalize_category("My Custom Tag"), "My Custom Tag");
    }

    #[test]
    fn test_escape_latex() {
        assert_eq!(escape_latex("R&D at 100%"), "R\\&D at 100\\%");
        assert_eq!(escape_latex("C# and F#"), "C\\# and F\\#");
        assert_eq!(escape_latex("snake_case $5"), "snake\\_case \\$5");
        assert_eq!(escape_latex("~/dir ^top"), "\\textasciitilde{}/dir \\textasciicircum{}top");
        // Backslash and braces pass through so inline LaTeX still works.
        assert_eq!(escape_latex("\\textbf{bold}"), "\\textbf{bold}");
    }

    #[test]
    fn test_linkify_url_and_email() {
        let out = linkify_latex("See https://github.com/sinj3d or email me@x.com now");
        assert!(out.contains("\\href{https://github.com/sinj3d}{https://github.com/sinj3d}"));
        assert!(out.contains("\\href{mailto:me@x.com}{me@x.com}"));
        assert!(out.starts_with("See "));
    }

    #[test]
    fn test_linkify_peels_surrounding_punctuation() {
        // Leading paren and trailing ")." stay outside the link; the underscore
        // is escaped in the display text but kept raw in the href target.
        let out = linkify_latex("(https://x.com/a_b).");
        assert!(out.contains("(\\href{https://x.com/a_b}{https://x.com/a\\_b})."));
    }

    #[test]
    fn test_linkify_www_prefix_gets_scheme() {
        let out = linkify_latex("www.simonjin.ca");
        assert_eq!(out, "\\href{https://www.simonjin.ca}{www.simonjin.ca}");
    }

    #[test]
    fn test_linkify_leaves_non_links_and_specials_alone() {
        // No scheme/@ ⇒ not a link; specials still escape exactly like escape_latex.
        assert_eq!(linkify_latex("CI/CD and config.json"), "CI/CD and config.json");
        assert_eq!(linkify_latex("R&D 50%"), "R\\&D 50\\%");
        assert_eq!(linkify_latex("ping @handle re: R&D@home"), "ping @handle re: R\\&D@home");
    }

    #[test]
    fn test_bio_header_links_profile_urls() {
        let out = inject_bio_header(
            "% {INJECT_BIO_HEADER}",
            "Jane Doe",
            &[
                "Pittsburgh PA".to_string(),
                "jane@example.com".to_string(),
                "https://github.com/jane".to_string(),
            ],
        );
        assert!(out.contains("\\href{mailto:jane@example.com}{jane@example.com}"));
        assert!(out.contains("\\href{https://github.com/jane}{https://github.com/jane}"));
        // A plain, non-link detail is untouched.
        assert!(out.contains("Pittsburgh PA"));
    }

    #[test]
    fn test_inject_sections_headings_and_escaping() {
        let out = inject_sections_by_category(
            "% {INJECT_SECTIONS}",
            &[SectionGroup {
                heading: "Projects & Competitions".to_string(),
                entries: vec![entry("Robot", Some("R&D Club"), vec!["Won 1st of 50%"])],
            }],
        );
        assert!(out.contains("\\section*{Projects \\& Competitions}"));
        assert!(out.contains("Robot -- R\\&D Club"));
        assert!(out.contains("\\item Won 1st of 50\\%"));
        assert!(out.contains("\\begin{itemize}"));
    }

    #[test]
    fn test_inject_sections_skips_empty_groups() {
        let out = inject_sections_by_category(
            "% {INJECT_SECTIONS}",
            &[SectionGroup { heading: "Empty".to_string(), entries: vec![] }],
        );
        assert!(!out.contains("\\section*{Empty}"));
    }

    #[test]
    fn test_education_entry_rendering() {
        let edu_entry = ResumeEntry {
            title: "B.S. Computer Science".to_string(),
            org: Some("State University".to_string()),
            start: Some("2022".to_string()),
            end: Some("2026".to_string()),
            bullets: vec![],
            education: Some(crate::db::models::EducationDetails {
                experience_id: 1,
                degree: Some("B.S. Computer Science".to_string()),
                gpa: Some("3.87/4.0".to_string()),
                coursework: Some("Algorithms, Operating Systems".to_string()),
                honors: Some("Dean's List".to_string()),
            }),
        };
        let out = inject_sections_by_category(
            "% {INJECT_SECTIONS}",
            &[SectionGroup { heading: "Education".to_string(), entries: vec![edu_entry] }],
        );
        // Institution headlines the subsection; degree/GPA/coursework/honors follow.
        assert!(out.contains("\\subsection*{State University \\hfill 2022 -- 2026}"));
        assert!(out.contains("B.S. Computer Science \\textbar{} GPA: 3.87/4.0 \\par"));
        assert!(out.contains("\\emph{Relevant Coursework:} Algorithms, Operating Systems \\par"));
        assert!(out.contains("\\emph{Honors:} Dean's List \\par"));
    }

    #[test]
    fn test_education_entry_omits_empty_fields() {
        let edu_entry = ResumeEntry {
            title: "B.S. CS".to_string(),
            org: Some("State University".to_string()),
            start: None,
            end: None,
            bullets: vec![],
            education: Some(crate::db::models::EducationDetails {
                experience_id: 1,
                degree: None,
                gpa: None,
                coursework: None,
                honors: None,
            }),
        };
        let out = inject_sections_by_category(
            "% {INJECT_SECTIONS}",
            &[SectionGroup { heading: "Education".to_string(), entries: vec![edu_entry] }],
        );
        // Title falls back as the degree line; no GPA/coursework/honors lines.
        assert!(out.contains("B.S. CS \\par"));
        assert!(!out.contains("GPA:"));
        assert!(!out.contains("Relevant Coursework"));
        assert!(!out.contains("Honors:"));
    }

    #[test]
    fn test_bio_header_uses_namesize_and_divider() {
        let out = inject_bio_header("% {INJECT_BIO_HEADER}", "Jane Doe", &[]);
        assert!(out.contains("{\\namesize \\textbf{Jane Doe}}"));
        assert!(out.contains("\\headerdivider"));
    }
}
